#!/bin/bash

# Define colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

if [ "$#" -ne 1 ]; then
    echo -e "${YELLOW}use command: torhost on/off${NC}"
    exit 1
fi

case "$1" in
    on)
        if [ "$(id -u)" -eq 0 ]; then
            systemctl start tor
            systemctl status tor | grep -E "Active" | sed 's/^[ \t]*//' | while IFS= read -r line; do echo -e "${GREEN}$line${NC}"; done
            echo -en "${YELLOW}Your URL: ${BLUE}"
            cat /var/lib/tor/hidden_service/hostname
            echo -e "${NC}${YELLOW}To stop: torhost off${NC}"
	    echo -e "${NC}${GREEN}Configaration file location : /etc/tor/torrc${NC}"
        else
            echo -e "${RED}You are not a root user${NC}"
        fi
        ;;
    off)
        if [ "$(id -u)" -eq 0 ]; then
            systemctl stop tor
            systemctl status tor | grep -E "Active" | sed 's/^[ \t]*//' | while IFS= read -r line; do echo -e "${GREEN}$line${NC}"; done
        else
            echo -e "${RED}You are not a root user${NC}"
        fi
        ;;
    *)
        echo -e "${YELLOW}use command: torhost on/off${NC}"
        exit 1
        ;;
esac
